name: Python CI

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
      MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
      MAIL_USE_SSL: ${{ secrets.MAIL_USE_SSL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MongoDB
        run: |
          docker run --name mongodb -p 27017:27017 -d mongo:latest
          sleep 5

      - name: Run tests with pytest
        run: |
          pytest
